### PR TITLE
Add children count fetchers

### PR DESCRIPTION
**Pull request by aguiraf**
This PR adds the functionality to count children objects to the new Graphql API.
Also adds other ad-hoc methods in order to list and count  deeply nested objects.
@abyrd , can be this one the way to go on for adding missing data to the API? 
or are you thinking in something different?
Let me know if there’s anything I can do to help.

commit summary:
- Add RowCountFilteredFetcher to get row count out of an SQL table filtered by parent join field
- Add some *_count fields to GraphQLGtfsSchema (e.g. stop_count and trip_count in patternType)
- Add fromStop() and fromStopCount() to RouteFetcher
- Add fromRoute() and fromRouteCount() to StopFetcher
- Add stops and stop_count to routeType in GraphQLGtfsSchema
- Add routes and route_count to stopType in GraphQLGtfsSchema

### CODE REVIEW

**Comment by abyrd** [comment]
Hi @aguiraf, can you provide some more context for this pull request? It's not clear to me what the objective of these changes is, since there is no accompanying ticket or discussion. What specifically are you working on and how are you using gtfs-api? We have been thinking of this as an internal Conveyal project and have in fact recently eliminated this project, merging most of its code into gtfs-lib. 

I will need to spend more time to understand this pull request, but at first glance it seems like there may be significant blocks of code devoted to special purpose requests (e.g. fromStopCount) and overall we have been trying to use only a few generic methods to fetch from various tables. I'm wary of adding special purpose code that will need to be maintained.

**Comment by aguiraf** [comment]
Hi @abyrd, thanks for replying.
Sorry, I will provide more context here, and next time I'll open an issue first.
We are trying to use the great datatool project, dev branch;
In the manager part, FeedVersionTabs are devoted to list & summarize  main feed entities with some counters.
The dev branch relies on the new graphql api which is being refactored and does not support all data requested yet.
We started working just on the counters to be rendered on the FeedVersionTabs, eg. # of trips. # of stops

The main objective of this PR is to provide a generic class to count "children" objects.
this is done in RowCountFilteredFetcher.java where we get row count out of SQL table filtered by parent join field,
basically issuing a sql like:

```select count(*) as row_count from patterns where route_id = %s```

This let us to count, in first analysis:

- the number of trips that use the pattern,

- the number of stops served by the pattern

- the number of trips defined for the route

- the number of patterns defined for the route

defining fields in GraphQLGtfsSchema as follows:

```
routeType = newObject().name("route")
[...]
.field(newFieldDefinition()
                    .name("pattern_count")
                    .description("The number of patterns defined for the route")
                    .type(GraphQLInt)
                    .dataFetcher(new RowCountFilteredFetcher("patterns", "route_id"))
                    .build()
```


There are other cases where the objects to count are not direct children of an entity, but more deeply nested, e.g:

- the number of routes that use a stop, or

- the number of stops ever used by a route

for such cases we had to join tables and to issue a <distinct> clause;

not being able to generalize, we wrote ad-hoc methods and we placed them in the relevant *Fetcher class, I know, not so manageable nor maintainable;

If it's still of some interest to you I could open an issue/discussion on gtfs-lib, possibly splitting cases and starting with the generic RowCountFilteredFetcher.

**Comment by abyrd** [comment]
@aguiraf thanks for the additional info. When you say "datatool project" which exact repo are you using? We are not actively working on the code under the Conveyal organization. Please note the text at the top of the old Conveyal repo: `DEVELOPMENT NOW HAPPENING ON FORK AT: https://github.com/catalogueglobal/datatools-server`

On this fork, Conveyal is working with several other companies / organizations to continue development of this system. The dev branch of that repo should be only a few commits behind the latest releases v3.1.0 and v3.2.0. That entire project should build properly against a recent gtfs-lib version with no gtfs-api. If you would like to work on this software, please get familiar with that repo.

Can you also clarify who "we" is in your message? Are you able to devote a certain amount of resources to collaborating on this project?

**Comment by aguiraf** [comment]
Hi @abyrd , yes we are aware of the https://github.com/catalogueglobal/datatools-server and ui forks, we are following their developement in conjunction with the gtfs-lib last enhancements involving graphql schema and RDBMS storage.
The datatools project builds properly against the new gtfs-lib but several parts need to be refactored yet, eg editor, feed summary.  @landonreed  and you are making a great work on it!
While getting familiar with the code, we are trying to adapt some small parts of the datatools-ui to the last gtfs-lib changes. 
We @5Tsrl  http://www.5t.torino.it are a small public company located in Turin Italy; we support local authorities (which own the company) in managing PT and ITS projects. In the past years we deployed some websites powered by OpenTripPlanner: www.muoversinpiemonte.it , www.muoversiatorino.it 
At the moment the team is composed by two of us: we're thinking to customize the datatools suite to respond to some authority's requests (eg service contracts, km); we would be glad to collaborate and re-contribute our work to the project.

**Comment by abyrd** [comment]
Hi @aguiraf, I just read up on 5T and checked out your Piemonte and Torino trip planners. I'm glad to see OTP being useful to one of my favorite towns :) Note that we now have the editor working with the RDBMS storage, and are currently testing that for deployment as soon as  we've established that all features have been migrated and are functioning stably.

For the time being, even under that new system we are not going to use GraphQL for the mutation queries. This is for purely pragmatic reasons, allowing us to concentrate on replacing the storage subsystem first before revising any API code. It leaves us for now with a weird hybrid API that fetches via GraphQL but stores via REST-ish calls, but it works.

Because all development is happening over there, and the `gtfs-api` definition is now merged into `gtfs-lib`, this repo will not be maintained. If you're still interested in using datatools we look forward to hearing from you on the `gtfs-lib` and other projects, but I'm going to close out tickets on this `gtfs-api` project.

**Pull request closed without merging**
